### ISSUE TITLE
扩展新模型出现错误

### ISSUE THREAD

**Issue by ioo0s** [Yu-Fangxu/COLD-Attack#1]
## 目的
想添加其他模型，例如chatglm

## 预期
正常运行，可以对抗训练

## 出现问题
COLD-Attack/util.py", line 38, in embed_inputs
```
probs = torch.cat((x_onehot.type(torch.FloatTensor), probs.type(torch.FloatTensor)), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64798 but got size 65024 for tensor number 1 in the list.
```
追踪上去发现 decode_suffix时tokenizer.encode(x_sys)[1:]的shape 为 (1,8, 64798)
但是soft_forward_y_计算后的shape为65024？ 

## 尝试解决
当我尝试直接将tokenizer.encode后的shape补全到65024后，会出现其他错误，

## 希望解决
作者是否有尝试过添加中文模型或者其他模型呢？如何解决不一致问题

最后非常感谢，希望作者能帮忙解决答疑一下该问题

**Comment by Yu-Fangxu** [comment]
谢谢反馈，
我们还没有尝试过中文模型，这里x_onehot的维度应该是[Batchsize, length, vocab_size(65024)]，你可以检查一下util.py中initialize函数中对应203行的logits中最后一维是否不是vocab_size。我不是很确定是否中文模型output的logits最后一维不是vocab_size，你可以检查一下

**Comment by ioo0s** [comment]
非常感谢，目前调试发现，确实是中文模型的输出的shape与llama2的不同。
