### ISSUE TITLE
Question about attack_paraphrase.py

### ISSUE THREAD

**Issue by AntiQuality** [Yu-Fangxu/COLD-Attack#11]
Thanks for your great effort! There're two questions about reproducing your work, and thank you for answering them in advance.

1. Line 63 writes `prompts_with_adv.extend(p_with_adv)`, which seems like a update of suffix? What's the paraphrase results in this code?
2. The results saved in line 64-68 do not be saved to files. What's the correct way to save the experimental results?

Thanks!

**Comment by Yu-Fangxu** [comment]
Hi Xun,
1. p_with_adv is the prefix + paraphrase. You could check prompt_with_adv in decoding_paraphrase.py and find that actually text_post is the generated paraphrase.
2. line 64-68 store generated paraphrased text into pandas Dataframe, then you can add "to_csv()" to save the results.

**Comment by AntiQuality** [comment]
Thanks, Fangxu!

Here's an example of saving results, for anyone who needed:

```python
results_file = os.path.join(fw, 'results.csv')
if os.path.exists(results_file):
    existing_results = pd.read_csv(results_file)
    combined_results = pd.concat([existing_results, results], ignore_index=True)
else:
    combined_results = results

combined_results.to_csv(results_file, index=False)
print(f'Results saved to {results_file}')
```
