### ISSUE TITLE
RuntimeError When Executing bash attack.sh 

### ISSUE THREAD

**Issue by carahsueh** [Yu-Fangxu/COLD-Attack#12]
While executing the commands bash attack.sh "paraphrase" and bash attack.sh "suffix", I encountered an error at data index 25. The detailed information is as follows. What could I do to fix the error? 

/code/COLD-Attack-main/util.py", line 205, in initialize
output = model.generate(x, max_length=length + x.shape[-1], do_sample=True, top_k=10)
……
next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by Yu-Fangxu** [comment]
Hi,
Could you check the logits of output and find if there are inf or nan? Or you can check if it is caused by transformer versions :) Feel free to ask if you still face these problems

**Comment by vietvo89** [comment]
Hi @carahsueh, did you observe something abnormal from `loss`?

e.g. `iter=15, loss=nan, flu_loss=nan, c_loss_1=nan, c_loss_2=nan, last_lr=0.1`
