### ISSUE TITLE
运行时间过长且没有输出结果

### ISSUE THREAD

**Issue by TheLiao233** [Yu-Fangxu/COLD-Attack#13]
您好，由于我无法使用Hugging face token来调用模型所以改成了下载模型到本地再调用，我的显卡是a6000，但是使用默认参数运行bash attack.sh "suffix"用了差不多十二个小时，最后虽然能自动停止但是在output文件夹中并没有任何文件，应该怎么解决这个问题呢？
以下是运行bash attack.sh "control"的结果，希望作者能够回答一下该问题，非常感谢！
![图片](https://github.com/user-attachments/assets/7959edad-a3df-49d5-bd57-fb41f3ffa3d6)

**Comment by Yu-Fangxu** [comment]
你好，如果你发现运行时间过长可以适当缩小batch size试试，还有你提到的保存输出问题，在：https://github.com/Yu-Fangxu/COLD-Attack/issues/11.  有写了样例代码，你可以参考一下然后加在attack_suffix.py的下面，把result输出到csv文件中
