### ISSUE TITLE
Evaluation Script Request

### ISSUE THREAD

**Issue by YerbaPage** [Yu-Fangxu/COLD-Attack#2]
Hi, thanks for your excellent work!

I'm trying to incorporate your framework into my research, but it seems the evaluation scripts for metrics such as ASR, PPL, BLEU, etc., are missing from the repository. Could you share the evaluation codes to conducting these evaluations? 

Your assistance would greatly help in understanding and extending your impactful work. Thanks in advance!

**Comment by Yu-Fangxu** [comment]
Hi, thanks for your appreciation ~

I update the repo with the evaluation metrics. You could check evaluate.py to run. The folder evaluation contains BLEU etc, you could check examples in evaluation/ensemble_scorer.py. Then it should work.
Feel free to ask if you have other questions

**Comment by YerbaPage** [comment]
Thanks for your quick response and the shared codes!

I've also observed that the results from running `bash attack.sh <type_of_attack>` are not being saved in the `outputs` directory. Would it be necessary to adjust the code in `attack_*.py` to ensure the results are properly saved?

**Comment by Yu-Fangxu** [comment]
Yes, you could modify the last few rows in attack_*.py and save the result with pandas (.to_csv). Then it should be properly saved

**Comment by YerbaPage** [comment]
Sure, I'll make those modifications to match the format for evaluation. Thanks!
