### ISSUE TITLE
Missing local dependencies mentioned in requirements.txt

### ISSUE THREAD

**Issue by ninjanimus** [Yu-Fangxu/COLD-Attack#3]
Hi, this project seems interesting. When I tried to test this on Windows 11 host, getting the below error. Can someone help me solving this issue. Thanks!

```Powershell
(venv) PS F:\...\tools\COLD-Attack> pip install -r .\requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing f:\tmp\abs_ecyw11_7ze\croots\recipe\brotli-split_1659616059936\work (from -r .\requirements.txt (line 22))
ERROR: Brotli@ file:///tmp/abs_ecyw11_7ze/croots/recipe/brotli-split_1659616059936/work from file:///tmp/abs_ecyw11_7ze/croots/recipe/brotli-split_1659616059936/work (from -r .\requirements.txt (line 22)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.```

**Comment by adamtrnguyen** [comment]
hello ninjaminus the authors of this github repo accidentally specified the packages from their local directory. 
They used `pip freeze > requirements.txt` instead of `pip freeze | grep -v "file://" > requirements.txt`

I attached my requirements.txt that adapted to make the directory work. I hope it works for you as well. 

My configuration works for cuda 12.2.
[requirements.txt](https://github.com/Yu-Fangxu/COLD-Attack/files/14667186/requirements.txt)

**Comment by Yu-Fangxu** [comment]
Great thanks to Adanato for replying! If the problem is solved, this issue will be closed. If you have other questions, feel free to raise a new one.

**Comment by ninjanimus** [comment]
Thanks Adanato and Yu-Fangxu for the updates!
Unfortunately the newly provided requirements.txt failed to install. Most probably issue is from my end.

I have manually installed the missing modules as per the code one by one. Able to get the script into running state. Below are the requirements.txt that worked for me on Windows 11. I have also created a Pull request (https://github.com/Yu-Fangxu/COLD-Attack/pull/4) if that helps. Thanks!

```
accelerate==0.28.0
appdirs==1.4.4
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cycler==0.12.1
docker-pycreds==0.4.0
filelock==3.13.1
fonttools==4.50.0
fsspec==2024.3.1
gitdb==4.0.11
GitPython==3.1.42
huggingface-hub==0.21.4
idna==3.6
Jinja2==3.1.3
joblib==1.3.2
kiwisolver==1.4.5
MarkupSafe==2.1.5
matplotlib==3.8.3
mpmath==1.3.0
networkx==3.2.1
nltk==3.8.1
numpy==1.26.4
packaging==24.0
pandas==2.2.1
pillow==10.2.0
protobuf==4.25.3
psutil==5.9.8
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
safetensors==0.4.2
seaborn==0.13.2
sentencepiece==0.2.0
sentry-sdk==1.43.0
setproctitle==1.3.3
setuptools==69.2.0
six==1.16.0
smmap==5.0.1
sympy==1.12
tokenizers==0.15.2
torch==2.2.1
torchaudio==2.2.1
torchvision==0.17.1
tqdm==4.66.2
transformers==4.39.0
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
wandb==0.16.4
```
