### ISSUE TITLE
Have you evluated the method on the Harmful String Setting?

### ISSUE THREAD

**Issue by xszheng2020** [Yu-Fangxu/COLD-Attack#5]
Hi, @Yu-Fangxu 

Thanks for your great work.

Have you evaluated the method on the Harmful String Setting in Zou et al., 2023?

And, why are the ASRs so high on Llama 2 compared to those reported in Zou et al., 2023?

Are the Harmful Behavior Settings different?

Thanks!

[Arxiv 2023] Zou et al. Universal and Transferable Adversarial Attacks on Aligned Language Models. 2023

<img width="1577" alt="截屏2024-03-22 下午9 54 50" src="https://github.com/Yu-Fangxu/COLD-Attack/assets/101038474/55f10599-e253-48de-b922-524a9badf1c1">
<img width="1569" alt="截屏2024-03-22 下午9 58 01" src="https://github.com/Yu-Fangxu/COLD-Attack/assets/101038474/75e94ed6-c259-4267-bbdf-82f0cc859580">

**Comment by ZJUshine** [comment]
Maybe because the authors select 50 samples from advbench datasets

**Comment by Yu-Fangxu** [comment]
Hi Xiaosen,
1. Have you evaluated the method on the Harmful String Setting in [1]?
We have not yet conducted experiments on that part of the Advbench dataset.
2. Why are the ASRs so high on Llama 2 compared to those reported in [1], are the Harmful Behavior Settings different?
Different from GCG[1], we conduct experiments on a subset of the Advbench dataset, proposed by [2], which differs from the GCG uses, therefore the ASR might be different.

[1] Universal and Transferable Adversarial Attacks on Aligned Language Models
[2] Jailbreaking Black Box Large Language Models in Twenty Queries

**Comment by xszheng2020** [comment]
Thanks!
