### ISSUE TITLE
Authors need to clean the repostory a bit.

### ISSUE THREAD

**Issue by Junjie-Chu** [Yu-Fangxu/COLD-Attack#8]
Hello, 
I find many issues reported due to the inproper settings/cache_path/cuda. I could correct them but if you can clean the repostory and convert it to a more portable version will make it more impactful and easier to use.

Thank you for your open source spirit and hard work. Have a nice day! :)

**Comment by xi1ngang** [comment]
Thanks for the suggestion. We have updated the instruction for the setup of environment. Please let us know if you have further questions.
